title: Survive the August
email: info+sta@sglorch.de
description: Survive the August Minecraft Projekt
baseurl: "" 
url: ""
github_username:  sglorch
future: true
#theme: minima
#theme: just-the-docs
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

navbar-links:
  Discord (Saloon): "https://discord.gg/CyrYpfSmjk"
  Karte: "https://map.sta.sglorch.de/"

url-pretty: "STA.sglorch.de"

navbar-col: "#d5f5ea"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#fffffc"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#dcedca"
footer-text-col: "#777777"
footer-link-col: "#404040"
